### ISSUE TITLE
No description provided about the repository

### ISSUE THREAD

**Issue by naman653** [sugarlabs/flipsticks#4]
Their is no clue provided about the purpose of repository. Also **readme** file is also incomplete

**Comment by quozl** [comment]
Do you have a fix?

**Comment by naman653** [comment]
No, I got no idea about what this repository is about. That can happen to others also. I want to contribute but without any description provided, why would someone will contribute to the project.

**Comment by quozl** [comment]
Thanks!  We have several repositories with the same problem.  This particular repository is the source code for a Sugar activity, so one of the best files that describe the repository is [activity.info](https://github.com/sugarlabs/flipsticks/blob/master/activity/activity.info) which says

```
summary   = Using keyframes, program a stick figure to twist and dance
description = Flipsticks is a keyframe animation activity that lets you pose
            and program a stick figure to walk, run, rotate, twist, tumble and
            dance. You can save your animations to the journal and will soon be
            able to share them via the mesh. Flipsticks can be used to explore
            concepts in geometry, computer programming and animation; it helps
            develop spatial and analytical thinking skills. 
```

The Sugar app store also has an entry; http://activities.sugarlabs.org/en-US/sugar/addon/4044

Hope that helps.
